// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class StudentV2Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void studentV2() {
    // Test name: Student_V2
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("http://localhost:8080/");
    // 2 | setWindowSize | 1680x971 |  | 
    driver.manage().window().setSize(new Dimension(1680, 971));
    // 3 | click | css=.form-label-group:nth-child(1) > label |  | 
    driver.findElement(By.cssSelector(".form-label-group:nth-child(1) > label")).click();
    // 4 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it");
    // 5 | click | css=.form-label-group:nth-child(2) > label |  | 
    driver.findElement(By.cssSelector(".form-label-group:nth-child(2) > label")).click();
    // 6 | click | css=.form-label-group:nth-child(2) > label |  | 
    driver.findElement(By.cssSelector(".form-label-group:nth-child(2) > label")).click();
    // 7 | type | id=inputPassword | FraCalifano1 | 
    driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1");
    // 8 | click | css=.btn |  | 
    driver.findElement(By.cssSelector(".btn")).click();
    // 9 | click | css=.swal-button |  | 
    driver.findElement(By.cssSelector(".swal-button")).click();
    // 10 | click | linkText=Visualizza Bando |  | 
    driver.findElement(By.linkText("Visualizza Bando")).click();
    // 11 | click | css=.nav-item:nth-child(5) p |  | 
    driver.findElement(By.cssSelector(".nav-item:nth-child(5) p")).click();
    // 12 | click | linkText=Logout |  | 
    driver.findElement(By.linkText("Logout")).click();
    // 13 | click | css=.swal-button |  | 
    driver.findElement(By.cssSelector(".swal-button")).click();
  }
}
