// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Student_V2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Student_V2', async function() {
    // Test name: Student_V2
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1680x971 |  | 
    await driver.manage().window().setRect(1680, 971)
    // 3 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 4 | type | id=inputUsername | f.califano@studenti.unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("f.califano@studenti.unisa.it")
    // 5 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 6 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 7 | type | id=inputPassword | FraCalifano1 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("FraCalifano1")
    // 8 | click | css=.btn |  | 
    await driver.findElement(By.css(".btn")).click()
    // 9 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 10 | click | linkText=Visualizza Bando |  | 
    await driver.findElement(By.linkText("Visualizza Bando")).click()
    // 11 | click | css=.nav-item:nth-child(5) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(5) p")).click()
    // 12 | click | linkText=Logout |  | 
    await driver.findElement(By.linkText("Logout")).click()
    // 13 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
  })
})
