// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Admin_V2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Admin_V2', async function() {
    // Test name: Admin_V2
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1680x971 |  | 
    await driver.manage().window().setRect(1680, 971)
    // 3 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 4 | type | id=inputUsername | a.marino@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("a.marino@unisa.it")
    // 5 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 6 | type | id=inputPassword | andre123 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("andre123")
    // 7 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 8 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 9 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 10 | click | id=inputUsername |  | 
    await driver.findElement(By.id("inputUsername")).click()
    // 11 | type | id=inputUsername | a.marino@unisa.it | 
    await driver.findElement(By.id("inputUsername")).sendKeys("a.marino@unisa.it")
    // 12 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 13 | type | id=inputPassword | andrea123 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("andrea123")
    // 14 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 15 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 16 | click | css=.nav-item:nth-child(4) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(4) p")).click()
    // 17 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 18 | type | id=inputNameCI | Alice | 
    await driver.findElement(By.id("inputNameCI")).sendKeys("Alice")
    // 19 | type | id=inputSurnameCI | Vidoni | 
    await driver.findElement(By.id("inputSurnameCI")).sendKeys("Vidoni")
    // 20 | type | id=inputEmailCI | ali | 
    await driver.findElement(By.id("inputEmailCI")).sendKeys("ali")
    // 21 | sendKeys | id=inputEmailCI | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputEmailCI")).sendKeys(Key.ENTER)
    // 22 | click | id=inputEmailCI |  | 
    await driver.findElement(By.id("inputEmailCI")).click()
    // 23 | type | id=inputEmailCI | alice.vidoni@gmail.com | 
    await driver.findElement(By.id("inputEmailCI")).sendKeys("alice.vidoni@gmail.com")
    // 24 | click | css=.form-label-group:nth-child(5) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(5) > label")).click()
    // 25 | type | id=inputPassword | alicepiccola123 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("alicepiccola123")
    // 26 | click | css=.form-label-group:nth-child(6) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(6) > label")).click()
    // 27 | type | id=inputRePassword | alicepiccola123 | 
    await driver.findElement(By.id("inputRePassword")).sendKeys("alicepiccola123")
    // 28 | click | id=send |  | 
    await driver.findElement(By.id("send")).click()
    // 29 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 30 | click | css=.nav-item:nth-child(5) p |  | 
    await driver.findElement(By.css(".nav-item:nth-child(5) p")).click()
    // 31 | click | id=tipo |  | 
    await driver.findElement(By.id("tipo")).click()
    // 32 | select | id=tipo | label=Commissione Internazionale | 
    {
      const dropdown = await driver.findElement(By.id("tipo"))
      await dropdown.findElement(By.xpath("//option[. = 'Commissione Internazionale']")).click()
    }
    // 33 | click | css=.card:nth-child(4) #delUser |  | 
    await driver.findElement(By.css(".card:nth-child(4) #delUser")).click()
    // 34 | mouseOver | css=.card:nth-child(4) #delUser |  | 
    {
      const element = await driver.findElement(By.css(".card:nth-child(4) #delUser"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 35 | mouseOut | css=.card:nth-child(4) #delUser |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 36 | click | css=.swal-button--confirm |  | 
    await driver.findElement(By.css(".swal-button--confirm")).click()
    // 37 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 38 | click | css=.card:nth-child(4) #delUser |  | 
    await driver.findElement(By.css(".card:nth-child(4) #delUser")).click()
    // 39 | click | css=.swal-button--confirm |  | 
    await driver.findElement(By.css(".swal-button--confirm")).click()
    // 40 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 41 | click | linkText=Logout |  | 
    await driver.findElement(By.linkText("Logout")).click()
    // 42 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
  })
})
