// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CommissarioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void commissario() {
    // Test name: Commissario
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://localhost:8080/");
    // 2 | setWindowSize | 1680x971 | 
    driver.manage().window().setSize(new Dimension(1680, 971));
    // 3 | click | css=.form-label-group:nth-child(1) > label | 
    driver.findElement(By.cssSelector(".form-label-group:nth-child(1) > label")).click();
    // 4 | type | id=inputUsername | salvatore.amideo@commis.internazione.com
    driver.findElement(By.id("inputUsername")).sendKeys("salvatore.amideo@commis.internazione.com");
    // 5 | click | css=.form-label-group:nth-child(2) > label | 
    driver.findElement(By.cssSelector(".form-label-group:nth-child(2) > label")).click();
    // 6 | type | id=inputPassword | salvo123
    driver.findElement(By.id("inputPassword")).sendKeys("salvo123");
    // 7 | sendKeys | id=inputPassword | ${KEY_ENTER}
    driver.findElement(By.id("inputPassword")).sendKeys(Keys.ENTER);
    // 8 | click | css=.swal-button | 
    driver.findElement(By.cssSelector(".swal-button")).click();
    // 9 | click | css=.nav > .nav-item:nth-child(2) > a | 
    driver.findElement(By.cssSelector(".nav > .nav-item:nth-child(2) > a")).click();
    // 10 | click | id=inputDate | 
    driver.findElement(By.id("inputDate")).click();
    // 11 | type | id=inputDate | 2021-06-25
    driver.findElement(By.id("inputDate")).sendKeys("2021-06-25");
    // 12 | type | id=inputDate | 2021-06-30
    driver.findElement(By.id("inputDate")).sendKeys("2021-06-30");
    // 13 | click | id=inputSchedule | 
    driver.findElement(By.id("inputSchedule")).click();
    // 14 | type | id=inputSchedule | 09:00
    driver.findElement(By.id("inputSchedule")).sendKeys("09:00");
    // 15 | click | css=.card:nth-child(2) .btn | 
    driver.findElement(By.cssSelector(".card:nth-child(2) .btn")).click();
    // 16 | click | css=.swal-button | 
    driver.findElement(By.cssSelector(".swal-button")).click();
    // 17 | click | css=.nav > .nav-item:nth-child(3) > a | 
    driver.findElement(By.cssSelector(".nav > .nav-item:nth-child(3) > a")).click();
    // 18 | click | css=.fc-allow-mouse-resize .fc-title | 
    driver.findElement(By.cssSelector(".fc-allow-mouse-resize .fc-title")).click();
    // 19 | click | css=.nav-item:nth-child(4) > a | 
    driver.findElement(By.cssSelector(".nav-item:nth-child(4) > a")).click();
    // 20 | click | css=.card:nth-child(3) #inputPunteggio | 
    driver.findElement(By.cssSelector(".card:nth-child(3) #inputPunteggio")).click();
    // 21 | type | css=.card:nth-child(3) #inputPunteggio | 56
    driver.findElement(By.cssSelector(".card:nth-child(3) #inputPunteggio")).sendKeys("56");
    // 22 | click | css=.card:nth-child(3) .btn | 
    driver.findElement(By.cssSelector(".card:nth-child(3) .btn")).click();
    // 23 | click | css=.swal-button | 
    driver.findElement(By.cssSelector(".swal-button")).click();
    // 24 | click | linkText=Logout | 
    driver.findElement(By.linkText("Logout")).click();
    // 25 | click | css=.swal-button | 
    driver.findElement(By.cssSelector(".swal-button")).click();
  }
}
