// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Commissario', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Commissario', async function() {
    // Test name: Commissario
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    await driver.get("http://localhost:8080/")
    // 2 | setWindowSize | 1680x971 |  | 
    await driver.manage().window().setRect(1680, 971)
    // 3 | click | css=.form-label-group:nth-child(1) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(1) > label")).click()
    // 4 | type | id=inputUsername | salvatore.amideo@commis.internazione.com | 
    await driver.findElement(By.id("inputUsername")).sendKeys("salvatore.amideo@commis.internazione.com")
    // 5 | click | css=.form-label-group:nth-child(2) > label |  | 
    await driver.findElement(By.css(".form-label-group:nth-child(2) > label")).click()
    // 6 | type | id=inputPassword | salvo123 | 
    await driver.findElement(By.id("inputPassword")).sendKeys("salvo123")
    // 7 | sendKeys | id=inputPassword | ${KEY_ENTER} | 
    await driver.findElement(By.id("inputPassword")).sendKeys(Key.ENTER)
    // 8 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 9 | click | css=.nav > .nav-item:nth-child(2) > a |  | 
    await driver.findElement(By.css(".nav > .nav-item:nth-child(2) > a")).click()
    // 10 | click | id=inputDate |  | 
    await driver.findElement(By.id("inputDate")).click()
    // 11 | type | id=inputDate | 2021-06-25 | 
    await driver.findElement(By.id("inputDate")).sendKeys("2021-06-25")
    // 12 | type | id=inputDate | 2021-06-30 | 
    await driver.findElement(By.id("inputDate")).sendKeys("2021-06-30")
    // 13 | click | id=inputSchedule |  | 
    await driver.findElement(By.id("inputSchedule")).click()
    // 14 | type | id=inputSchedule | 09:00 | 
    await driver.findElement(By.id("inputSchedule")).sendKeys("09:00")
    // 15 | click | css=.card:nth-child(2) .btn |  | 
    await driver.findElement(By.css(".card:nth-child(2) .btn")).click()
    // 16 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 17 | click | css=.nav > .nav-item:nth-child(3) > a |  | 
    await driver.findElement(By.css(".nav > .nav-item:nth-child(3) > a")).click()
    // 18 | click | css=.fc-allow-mouse-resize .fc-title |  | 
    await driver.findElement(By.css(".fc-allow-mouse-resize .fc-title")).click()
    // 19 | click | css=.nav-item:nth-child(4) > a |  | 
    await driver.findElement(By.css(".nav-item:nth-child(4) > a")).click()
    // 20 | click | css=.card:nth-child(3) #inputPunteggio |  | 
    await driver.findElement(By.css(".card:nth-child(3) #inputPunteggio")).click()
    // 21 | type | css=.card:nth-child(3) #inputPunteggio | 56 | 
    await driver.findElement(By.css(".card:nth-child(3) #inputPunteggio")).sendKeys("56")
    // 22 | click | css=.card:nth-child(3) .btn |  | 
    await driver.findElement(By.css(".card:nth-child(3) .btn")).click()
    // 23 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
    // 24 | click | linkText=Logout |  | 
    await driver.findElement(By.linkText("Logout")).click()
    // 25 | click | css=.swal-button |  | 
    await driver.findElement(By.css(".swal-button")).click()
  })
})
